export const method = ['get','post']  
export const SSG = {
    id:'title',
    script:false
}
export default (request)=>{
    const title = request.query.title;
    if(request.method === 'post' && request.query.shell === 'update'){
        request.updateSSG('test'); //  Update title to be equal to the HTML file generated by test
        return {title}
    }else{
        if(title){
            return {title}
        }else{
            throw new Error('The title parameter cannot be empty')
        }
    }
}